### PR TITLE
Update for Symfony 5

### PR DESCRIPTION
**Pull request by BrandonFlude**
Command must return an INT, often 0 - update Composer to accept 5.0.* versions of Symfony packages.

### CODE REVIEW

**Comment by Gemineye** [comment]
Are there any plans to merge this PR?

**Comment by BrandonFlude** [comment]
@Gemineye, awaiting response from the developer.

**Comment by Phobetor** [comment]
@BrandonFlude thank you very much for you contribution!
Can you please remove the fork hint in the readme from the pull request?
It makes no sense to merge it.

**Comment by BrandonFlude** [comment]
@Phobetor  - sure can.

**Comment by BrandonFlude** [comment]
@Phobetor  - any chance we can get a tag out for this so we can pull through composer with the latest version? Thanks!

**Comment by Gemineye** [comment]
> @Phobetor - any chance we can get a tag out for this so we can pull through composer with the latest version? Thanks!

+1

**Comment by Phobetor** [comment]
Hi @BrandonFlude

Thank you very much for this pull request!

It is released in version `3.2.2`.

(fyi @Gemineye )

**Comment by Gemineye** [comment]
@Phobetor thanks! Maybe you should remove the usage of kernel.root_dir. I had to add this paramter:

kernel.root_dir: '%kernel.project_dir%'

**Pull request merged**
