### PR TITLE
fix `old_sound_rabbit_mq` configuration not properly detected when declared in multiple configuration files

### LINKED ISSUE #18: [BUG] OldSound rabbitmq bundle configuration not detected properly
In our project part of the `old_sound_rabbit_mq` configuration is defined in a shared bundle, and another part in the actual project configuration. This causes a bug in the auto-configuration of rabbitmq-supervisor-bundle where `consumers` and `multiple_consumers` are not detected. 

You can reproduce the bug by simply having parts of the configuration in different files.

### PR DESCRIPTION
**Pull request by spdionis**
This fixes #18.

Tested on my project and configuration is properly detected.

### CODE REVIEW

**Comment by ahilles107** [comment]
👍  - have this same problem, wanted to create PR also but found this one. What's the problem with merging it?

**Comment by ahilles107** [comment]
ping?

**Comment by czende** [comment]
Thanks for this PR. Any updates? This is a must feature!

**Comment by Phobetor** [comment]
Thank you very much for this pull request!

It is merged to dev-master and released in version [3.0.0](https://github.com/Phobetor/rabbitmq-supervisor-bundle/releases/tag/3.0.0).

**Pull request merged**
